// WorkDay Online 2026 — Data Layer
// Design: Clean Productivity Tool (Swiss International Style + Contemporary SaaS)
// Colors: Indigo-600 primary, Slate tones, Green/Amber for status

export type WorkStatus = "completed" | "pending" | "cancelled";

export interface WorkRecord {
  id: number;
  date: string; // YYYY-MM-DD
  month: Month;
  customer_name: string;
  customer_phone: string;
  product: string;
  os: string;
  service_type: string;
  details: string[];
  notes: string[];
  status: WorkStatus;
  images: WorkImage[];
}

export interface WorkImage {
  id: string; // UUID or unique identifier
  url: string; // S3 CDN URL
  filename: string;
  uploadedAt: string; // ISO date string
}

const STORAGE_KEY = "workday_records_2026";

const initialData: WorkRecord[] = [
  {
    id: 1,
    date: "2026-01-05",
    month: "ม.ค.",
    customer_name: "ออย",
    customer_phone: "0998299804",
    product: "MB40_VL_ID",
    os: "Windows 11",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "1 Windows 11",
      "2 ลงเวลาอย่างเดียว",
      "ออย 0998299804",
      "MB40_VL_ID",
      "ตั้งค่าพื้นฐาน",
      "ทางร้านรีโมท ลงโปรแกรม พื้นฐาน และแนะนำการใช้งานเบื้องต้น",
      "@ป๊อป รบกวนค่ะ",
    ],
    notes: [
      "ติดต่อไป 06-01-2025 14.00 ขอเลือนเป็น 16.00น",
      "ติดต่อไปตอน 16.30 ลค.แจ้ง ฝ้ายจัดซื้อนำเครื่องกลับไปแล้วหากได้เครื่องวันใหนจะติดต่อมาเอง",
    ],
    status: "pending",
    images: [],
  },
  {
    id: 2,
    date: "2026-01-05",
    month: "ม.ค.",
    customer_name: "",
    customer_phone: "0647797792",
    product: "MB10_VL_ID",
    os: "",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "ลูกค้าซื้อ MB10_VL_ID(WIFI) ไปค่ะ อยากได้ช่างเซ็ทระบบให้ วันพุธช่วงบ่าย @ป๊อป สะดวกไหมคะ",
      "เบอร์ช่างแอ็ดค่ะ 0647797792 ขออนุญาตแนะนำไลน์พี่ป๊อบให้ลูกค้านะคะ",
    ],
    notes: ["คุณดนัยจัดการ"],
    status: "pending",
    images: [],
  },
  {
    id: 3,
    date: "2026-01-09",
    month: "ม.ค.",
    customer_name: "กุ้ง",
    customer_phone: "0814068529",
    product: "MB10",
    os: "Windows 10",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "1.windows 10",
      "2.ลงเวลาแบบสแกนหน้า",
      "กุ้ง/0814068529",
      "MB10+ID+WIFI",
      "ต้องการรีโมทตั้งค่าเชิงลึก",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
    ],
    notes: ["zlink ok"],
    status: "completed",
    images: [],
  },
  {
    id: 4,
    date: "2026-01-12",
    month: "ม.ค.",
    customer_name: "",
    customer_phone: "0630825371",
    product: "SenseFace 2A",
    os: "",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: ["ลูกค้าซื้อ SenseFace 2A ต้องการให้รีโมทให้ค่ะ 063-0825371"],
    notes: ["zlink ok"],
    status: "completed",
    images: [],
  },
  {
    id: 5,
    date: "2026-01-14",
    month: "ม.ค.",
    customer_name: "กิต",
    customer_phone: "0811513740",
    product: "SenseFace 4A",
    os: "Windows 11",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "SenseFace 4A",
      "windows 11, ใช้เป็นแบบสแกนนิ้ว แสกนหน้า และลงเวลา",
      "นัดเป็นวันที่ 14 ตั่งแต่ 09.00 เป็นต้นไปค่ะ",
      "081-1513740 ชื่อ กิต นะคะ",
      "รีโมทติดตั้ง/ตั้งค่า",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
      "@POP",
    ],
    notes: ["Zlink"],
    status: "pending",
    images: [],
  },
  {
    id: 6,
    date: "2026-01-19",
    month: "ม.ค.",
    customer_name: "ณัฐชยา",
    customer_phone: "0635156495",
    product: "SenseFace 2A",
    os: "Windows 11",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "ณัฐชยา 0635156495",
      "ลงเวลา",
      "windows 11",
      "SenseFace 2A",
      "ต้องการรีโมทตั้งค่าเชิงลึก",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
    ],
    notes: ["12.00 ติดต่อไปใหม่", "Is OK"],
    status: "completed",
    images: [],
  },
  {
    id: 7,
    date: "2026-01-19",
    month: "ม.ค.",
    customer_name: "เสมียนมิ้ม",
    customer_phone: "0818656575",
    product: "SenseFace 2A",
    os: "Windows 10",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "SenseFace 2A",
      "1. windows 10",
      "2. สแกนนิ้ว ลงเวลา",
      "เสมียนมิ้ม 0818656575",
      "รีโมทติดตั้ง/ตั้งค่า",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
      "@POP",
    ],
    notes: ["is ok"],
    status: "completed",
    images: [],
  },
  {
    id: 8,
    date: "2026-01-19",
    month: "ม.ค.",
    customer_name: "ธีระ",
    customer_phone: "0923565469",
    product: "SenseFace 2A",
    os: "Windows 11",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "1. Windows11",
      "2. แสกนนิ้ว ลงเวลาเท่านั้น",
      "ธีระ 092-3565469",
      "ลงโปรแกรมวันนี้ 14.00น.",
      "SenseFace 2A",
      "ต้องการรีโมทตั้งค่าเชิงลึก",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
    ],
    notes: ["K'Danail รับจบ", "Is OK"],
    status: "completed",
    images: [],
  },
  {
    id: 9,
    date: "2026-01-21",
    month: "ม.ค.",
    customer_name: "K.dream",
    customer_phone: "",
    product: "",
    os: "Windows 11",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "D2026012101 K.dream",
      "1. windows ,11",
      "2. ใช้เป็นแบบสแกนนิ้วลงเวลา",
      "เจมส์ /0642942442",
    ],
    notes: ["is ok"],
    status: "completed",
    images: [],
  },
  {
    id: 10,
    date: "2026-01-21",
    month: "ม.ค.",
    customer_name: "",
    customer_phone: "",
    product: "",
    os: "Windows 10",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "-Windows 10 Pro",
      "-ลงเวลาด้วยสแกนนิ้ว",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
    ],
    notes: ["โทรไป 21/1/2026 เวลา 15.59"],
    status: "pending",
    images: [],
  },
  {
    id: 11,
    date: "2026-01-21",
    month: "ม.ค.",
    customer_name: "เปรี้ยวมาก",
    customer_phone: "",
    product: "",
    os: "",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: ["Ticket: 26012101 Sale : เปรี้ยวมาก"],
    notes: ["พุ่งนี้ 10 โมง"],
    status: "pending",
    images: [],
  },
  {
    id: 12,
    date: "2026-01-23",
    month: "ม.ค.",
    customer_name: "น้องดรีม",
    customer_phone: "",
    product: "",
    os: "",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: ["Ticket: 69012401 Sale : น้องดรีม"],
    notes: ["พรุ่งนี้ 10 โมง"],
    status: "pending",
    images: [],
  },
  {
    id: 13,
    date: "2026-01-27",
    month: "ม.ค.",
    customer_name: "",
    customer_phone: "",
    product: "",
    os: "",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: ["ขอนัดรีโมทวันนี้ ช่วงเวลา14.30-15.00 น."],
    notes: [],
    status: "pending",
    images: [],
  },
  {
    id: 14,
    date: "2026-01-28",
    month: "ม.ค.",
    customer_name: "",
    customer_phone: "",
    product: "SenseFace 2A",
    os: "Windows 11",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "SenseFace 2A",
      "windows 11",
      "สแกนนิ้ว ลงเวลา",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
    ],
    notes: ["is ok"],
    status: "completed",
    images: [],
  },
  {
    id: 15,
    date: "2026-01-29",
    month: "ม.ค.",
    customer_name: "",
    customer_phone: "",
    product: "MB10",
    os: "Windows 10",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "MB10",
      "windows 10",
      "ลงเวลา",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
    ],
    notes: ["is ok"],
    status: "completed",
    images: [],
  },
  {
    id: 16,
    date: "2026-01-30",
    month: "ม.ค.",
    customer_name: "",
    customer_phone: "",
    product: "SenseFace 2A",
    os: "Windows 11",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "SenseFace 2A",
      "windows 11",
      "สแกนนิ้ว ลงเวลา",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
    ],
    notes: ["is ok"],
    status: "completed",
    images: [],
  },
  {
    id: 17,
    date: "2026-01-30",
    month: "ม.ค.",
    customer_name: "",
    customer_phone: "",
    product: "MB10",
    os: "Windows 10",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "MB10",
      "windows 10",
      "ลงเวลา",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
    ],
    notes: ["is ok"],
    status: "completed",
    images: [],
  },
  {
    id: 18,
    date: "2026-01-31",
    month: "ม.ค.",
    customer_name: "",
    customer_phone: "",
    product: "SenseFace 2A",
    os: "Windows 11",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "SenseFace 2A",
      "windows 11",
      "สแกนนิ้ว ลงเวลา",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
    ],
    notes: [],
    status: "pending",
    images: [],
  },
  // ก.พ.
  {
    id: 19,
    date: "2026-02-02",
    month: "ก.พ.",
    customer_name: "คุณปลาย",
    customer_phone: "0840419990",
    product: "Biotime",
    os: "Linux",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "0840419990 =คุณปลาย ค่ะ",
      "รบกวนให้ IT ที่จะคอนฟิกให้ติดต่อกลับหน่อยนะคะ",
      "เขาเช่าคลาวเอง เป็น Linux จะให้เรารีโมทไปติดตั้งให้",
      "ลูกค้าจะซื้อบริการรีโมท รบกวนพี่ๆติดต่อลูกค้าค่ะ @POP",
      "เขาจะซื้อ License Biotime น่ะ",
    ],
    notes: [
      "ติดต่อไปเรียบร้อยคาป เขาอยากได้ไอเดีย ไม่รู้จะใช้ซอฟต์แวร์ใหน",
    ],
    status: "pending",
    images: [],
  },
  {
    id: 20,
    date: "2026-02-02",
    month: "ก.พ.",
    customer_name: "",
    customer_phone: "0994793956",
    product: "",
    os: "",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "ติดต่อเทคนิคให้หน่อยค่ะ",
      "มีปัญหาการตั้งค่าแอดมินหน้าเครื่อง รายชื่อที่มีหายหมดเลยค่ะ",
      "0994793956 @POP",
    ],
    notes: [
      "เลิกงานแล้ว พรุ่งนี้ 10 โมง",
      "3/2/2026 ไปโรงงานไปเอาของให้พี่บอล โทรแจ้ง ลค.ไม่ว่างในตอนเช้า นัดใหม่เป็น 04/02/2026 เวลา 10 โมง",
      "โทรไป 4/2/2026 เวลา 10.00 ขอเลื่อนอีกเป็น 14.00 น",
    ],
    status: "pending",
    images: [],
  },
  {
    id: 21,
    date: "2026-02-03",
    month: "ก.พ.",
    customer_name: "นายธนกร บุญมาสืบ",
    customer_phone: "0818712441",
    product: "EFace10",
    os: "Windows 11",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "EFace10",
      "windows 11",
      "แสกนหน้า ลงเวลา",
      "นายธนกร บุญมาสืบ 081-871-2441",
      "ต้องการรีโมทตั้งค่า/ตั้งค่า",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
    ],
    notes: [
      "โทรไป 4/2/2026 เวลา 09.13 ไม่รับ",
      "โทรไป 4/2/2026 เวลา 10.13 ไม่รับ",
      "10.14 ลค.ติดต่อกลับมา ขอวันนี้ อาจเป็นเวลา 14.00-15-00",
    ],
    status: "pending",
    images: [],
  },
  {
    id: 22,
    date: "2026-02-04",
    month: "ก.พ.",
    customer_name: "อนงค์นาฎ",
    customer_phone: "0929940357",
    product: "MB10",
    os: "Windows 10",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "1. windows 10",
      "2. สแกนนิ้วลงเวลาอย่างเดียวค่ะ",
      "อนงค์นาฎ 092-994-0357 สะดวกวันพุธ เวลา 11.00 ได้ค่ะ",
      "MB10 + ID +WIFI",
      "รีโมทตั้งค่าเชิงลึก ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
    ],
    notes: ["zlink ok"],
    status: "completed",
    images: [],
  },
  {
    id: 23,
    date: "2026-02-06",
    month: "ก.พ.",
    customer_name: "คุณพรทิพย์",
    customer_phone: "0925993562",
    product: "EFace10",
    os: "",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "EFace10",
      "ควบคุมเปิดปิดประตู",
      "คุณพรทิพย์ （ใบเตย) 092 599 3562",
      "06/02/69 13.30น.",
      "ร้านรีโมทติดตั้ง",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
      "@POP",
    ],
    notes: ["ขอเลื่อนไปวันจันที่ 9 +13.00 น."],
    status: "pending",
    images: [],
  },
  {
    id: 24,
    date: "2026-02-10",
    month: "ก.พ.",
    customer_name: "",
    customer_phone: "",
    product: "SenseFace 2A",
    os: "",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "SenseFace 2A = 1 เครื่อง",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
    ],
    notes: ["วันนี้บ่ายๆ 15:00 น"],
    status: "pending",
    images: [],
  },
  {
    id: 25,
    date: "2026-02-10",
    month: "ก.พ.",
    customer_name: "",
    customer_phone: "",
    product: "EFace10",
    os: "",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "EFace10 = 1 เครื่อง",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
    ],
    notes: ["พรุ่งนี้ 11/02/2026 เวลา 10 โมงเช้า"],
    status: "pending",
    images: [],
  },
  {
    id: 26,
    date: "2026-02-10",
    month: "ก.พ.",
    customer_name: "",
    customer_phone: "",
    product: "",
    os: "Windows Server",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "ถ้า server มันจะเป็น window server นะครับ",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
    ],
    notes: ["16.00 ติดต่อไปไหม ขอเลื่อน"],
    status: "pending",
    images: [],
  },
  {
    id: 27,
    date: "2026-02-16",
    month: "ก.พ.",
    customer_name: "",
    customer_phone: "",
    product: "",
    os: "Windows 11",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "1. Windows 11",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
    ],
    notes: [],
    status: "pending",
    images: [],
  },
  {
    id: 28,
    date: "2026-02-16",
    month: "ก.พ.",
    customer_name: "",
    customer_phone: "",
    product: "SenseFace 2A",
    os: "",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "SenseFace 2A = 1 ครื่อง",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
    ],
    notes: ["วันนี้ขอรบกวนแจ้งฝ่ายเทคนิคอีกรอบครับ"],
    status: "pending",
    images: [],
  },
  {
    id: 29,
    date: "2026-02-18",
    month: "ก.พ.",
    customer_name: "",
    customer_phone: "",
    product: "SenseFace 2A",
    os: "Windows 11",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "SenseFace 2A",
      "windows 11",
      "สแกนนิ้ว ลงเวลา",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
    ],
    notes: ["is ok"],
    status: "completed",
    images: [],
  },
  {
    id: 30,
    date: "2026-02-18",
    month: "ก.พ.",
    customer_name: "",
    customer_phone: "",
    product: "MB10",
    os: "Windows 10",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "MB10",
      "windows 10",
      "ลงเวลา",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
    ],
    notes: ["is ok"],
    status: "completed",
    images: [],
  },
  {
    id: 31,
    date: "2026-02-20",
    month: "ก.พ.",
    customer_name: "",
    customer_phone: "",
    product: "SenseFace 2A",
    os: "Windows 11",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "SenseFace 2A",
      "windows 11",
      "สแกนนิ้ว ลงเวลา",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
    ],
    notes: ["is ok"],
    status: "completed",
    images: [],
  },
  {
    id: 32,
    date: "2026-02-23",
    month: "ก.พ.",
    customer_name: "",
    customer_phone: "",
    product: "MB10",
    os: "Windows 10",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "MB10",
      "windows 10",
      "ลงเวลา",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
    ],
    notes: ["is ok"],
    status: "completed",
    images: [],
  },
  {
    id: 33,
    date: "2026-02-24",
    month: "ก.พ.",
    customer_name: "",
    customer_phone: "",
    product: "SenseFace 2A",
    os: "Windows 11",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "SenseFace 2A",
      "windows 11",
      "สแกนนิ้ว ลงเวลา",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
    ],
    notes: [],
    status: "pending",
    images: [],
  },
  {
    id: 34,
    date: "2026-02-25",
    month: "ก.พ.",
    customer_name: "",
    customer_phone: "",
    product: "MB10",
    os: "Windows 10",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "MB10",
      "windows 10",
      "ลงเวลา",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
    ],
    notes: [],
    status: "pending",
    images: [],
  },
  {
    id: 35,
    date: "2026-02-26",
    month: "ก.พ.",
    customer_name: "",
    customer_phone: "",
    product: "SenseFace 2A",
    os: "Windows 11",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "SenseFace 2A",
      "windows 11",
      "สแกนนิ้ว ลงเวลา",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
    ],
    notes: [],
    status: "pending",
    images: [],
  },
  {
    id: 36,
    date: "2026-02-27",
    month: "ก.พ.",
    customer_name: "",
    customer_phone: "",
    product: "MB10",
    os: "Windows 10",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "MB10",
      "windows 10",
      "ลงเวลา",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
    ],
    notes: [],
    status: "pending",
    images: [],
  },
  // มี.ค.
  {
    id: 37,
    date: "2026-03-02",
    month: "มี.ค.",
    customer_name: "นิสาชล ผ่องผล",
    customer_phone: "0910073126",
    product: "K60",
    os: "Windows 10",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "K60 = 1 เครื่อง",
      "ใช้ windows 10 pro",
      "สแกนนิ้วลงเวลา",
      "นิสาชล ผ่องผล",
      "0910073126",
      "ต้องการรีโมทตั้งค่า/ตั้งค่า",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
    ],
    notes: ["zktimnet ok"],
    status: "completed",
    images: [],
  },
  {
    id: 38,
    date: "2026-03-02",
    month: "มี.ค.",
    customer_name: "คุณฝน",
    customer_phone: "0818855431",
    product: "SenseFace 2A",
    os: "Windows 10",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "1.windows10",
      "2.แสกนนิ้วลงเวลา ไม่ต้องควบคุมเปิดปิดประตู",
      "ชื่อ คุณฝน 081-885-5431",
      "เวลาที่สะดวก วันนี้(2มี.ค.)11:00-15:00น",
      "ติดปัญหา เพิ่มนิ้ว กับ ตั้งกะและดูรายงาน ไม่ใช้งานใหม่ เป็นงาน Services ลืมเองเพราะไม่ได้ใช่",
      "SenseFace 2A",
      "รีโมทติดตั้ง/ตั้งค่า",
    ],
    notes: ["is ok"],
    status: "completed",
    images: [],
  },
  {
    id: 39,
    date: "2026-03-04",
    month: "มี.ค.",
    customer_name: "รัชพล หวังสม",
    customer_phone: "0909465566",
    product: "MB10",
    os: "Windows 10",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "วินโด10",
      "สแกนลงเวลางาน และ เวลาเลิกงาน ครับ",
      "รัชพล หวังสม",
      "0909465566",
      "11.30น. ครับ",
      "MB10",
      "รีโมทติดตั้ง/ตั้งค่า",
    ],
    notes: [
      "นัดพรุ่งนี้ 5/3/2026 Time 11.30 เท่านั้น",
      "5/3/2026 คอมดำ ไปซ่อมจอดับ พอมาวันนี้เป็นอีกแล้วจอดับเปิดไม่ติด จะติดต่อกลับมาเองหลังซ่อมคอมเสร็จ",
      "นัดใหม่ 26/3/2026 เวลา 11.30",
    ],
    status: "pending",
    images: [],
  },
  {
    id: 40,
    date: "2026-03-06",
    month: "มี.ค.",
    customer_name: "พลอย",
    customer_phone: "0950459090",
    product: "MB10",
    os: "",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "MB10-VL-ID+WiFi =1",
      "(ลูกค้าเคยซื้อก่อนหน้า 1 เครื่อง พร้อมบริการรีโมทติดตั้ง/ตั้งค่า)",
      "Zlink",
      "ลงเวลางาน",
      "พลอย 0950459090",
      "สะดวกรีโมทได้เลยค่ะ",
      "ทางร้านรีโมท ลงโปรแกรม พื้นฐาน และแนะนำการใช้งานเบื้องต้นให้",
      "@POP",
    ],
    notes: ["OK"],
    status: "completed",
    images: [],
  },
  {
    id: 41,
    date: "2026-03-09",
    month: "มี.ค.",
    customer_name: "แพรพรรณ",
    customer_phone: "0848955650",
    product: "SenseFace 2A",
    os: "Windows 11",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "ZKTeco SenseFace 2A = 1",
      "Window 11",
      "ใช้แบบสแกนเข้าออกอย่างเดียวค่ะ",
      "แพรพรรณ 084-8955650",
      "ทางร้านรีโมท ลงโปรแกรม พื้นฐาน และแนะนำการใช้งานเบื้องต้นให้",
    ],
    notes: [
      "นัด",
      "11/3/2026 เวลาบ่ายโมงง",
      "โทรไปขอเลื่อนอีกเป็น 4 โมงเย็น",
    ],
    status: "pending",
    images: [],
  },
  {
    id: 42,
    date: "2026-03-10",
    month: "มี.ค.",
    customer_name: "",
    customer_phone: "",
    product: "SenseFace 2A",
    os: "",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "ZKTeco SenseFace 2A = 1",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
    ],
    notes: ["นัด 12/3/2026 เวลาบ่าย 3 โมงเป้นต้นไป"],
    status: "pending",
    images: [],
  },
  {
    id: 43,
    date: "2026-03-10",
    month: "มี.ค.",
    customer_name: "",
    customer_phone: "",
    product: "MB10",
    os: "",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "MB10-VL-ID+WiFi = 1 เครื่อง",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
    ],
    notes: [],
    status: "pending",
    images: [],
  },
  {
    id: 44,
    date: "2026-03-11",
    month: "มี.ค.",
    customer_name: "",
    customer_phone: "",
    product: "SenseFace 2A",
    os: "",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "SenseFace 2A = 1",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
    ],
    notes: ["นัด 13/3/2026 เวลา 14:00 น. เป็นต้นไป"],
    status: "pending",
    images: [],
  },
  {
    id: 45,
    date: "2026-03-11",
    month: "มี.ค.",
    customer_name: "",
    customer_phone: "",
    product: "SenseFace 3A",
    os: "",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "SenseFace 3A",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
    ],
    notes: [],
    status: "pending",
    images: [],
  },
  {
    id: 46,
    date: "2026-03-16",
    month: "มี.ค.",
    customer_name: "",
    customer_phone: "",
    product: "SenseFace 2A",
    os: "",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "SenseFace 2A = 1",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
    ],
    notes: [],
    status: "pending",
    images: [],
  },
  {
    id: 47,
    date: "2026-03-17",
    month: "มี.ค.",
    customer_name: "",
    customer_phone: "",
    product: "MB10",
    os: "Windows 10",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "MB10",
      "windows 10",
      "ลงเวลา",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
    ],
    notes: ["is ok"],
    status: "completed",
    images: [],
  },
  {
    id: 48,
    date: "2026-03-18",
    month: "มี.ค.",
    customer_name: "",
    customer_phone: "",
    product: "SenseFace 2A",
    os: "Windows 11",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "SenseFace 2A",
      "windows 11",
      "สแกนนิ้ว ลงเวลา",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
    ],
    notes: ["is ok"],
    status: "completed",
    images: [],
  },
  {
    id: 49,
    date: "2026-03-19",
    month: "มี.ค.",
    customer_name: "",
    customer_phone: "",
    product: "MB10",
    os: "Windows 10",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "MB10",
      "windows 10",
      "ลงเวลา",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
    ],
    notes: ["is ok"],
    status: "completed",
    images: [],
  },
  {
    id: 50,
    date: "2026-03-20",
    month: "มี.ค.",
    customer_name: "",
    customer_phone: "",
    product: "SenseFace 2A",
    os: "Windows 11",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "SenseFace 2A",
      "windows 11",
      "สแกนนิ้ว ลงเวลา",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
    ],
    notes: [],
    status: "pending",
    images: [],
  },
  {
    id: 51,
    date: "2026-03-23",
    month: "มี.ค.",
    customer_name: "",
    customer_phone: "",
    product: "MB10",
    os: "Windows 10",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "MB10",
      "windows 10",
      "ลงเวลา",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
    ],
    notes: [],
    status: "pending",
    images: [],
  },
  {
    id: 52,
    date: "2026-03-25",
    month: "มี.ค.",
    customer_name: "",
    customer_phone: "",
    product: "SenseFace 2A",
    os: "Windows 11",
    service_type: "รีโมทติดตั้ง/ตั้งค่า",
    details: [
      "SenseFace 2A",
      "windows 11",
      "สแกนนิ้ว ลงเวลา",
      "ทางร้านรีโมท ลงโปรแกรม แนะนำการใช้งาน / การตั้งกะ เวลา เข้าออกงาน / สอนดึงข้อมูล / Support ปัญหา",
    ],
    notes: [],
    status: "pending",
    images: [],
  },
];

// Load from localStorage or use initial data
export function loadRecords(): WorkRecord[] {
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored) {
      return JSON.parse(stored);
    }
  } catch (e) {
    console.error("Failed to load records:", e);
  }
  // Initialize with data
  saveRecords(initialData);
  return initialData;
}

export function saveRecords(records: WorkRecord[]): void {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(records));
  } catch (e) {
    console.error("Failed to save records:", e);
  }
}

export function getNextId(records: WorkRecord[]): number {
  if (records.length === 0) return 1;
  return Math.max(...records.map((r) => r.id)) + 1;
}

export const MONTHS = ["ม.ค.", "ก.พ.", "มี.ค."] as const;
export type Month = (typeof MONTHS)[number];

export const MONTH_LABELS: Record<string, string> = {
  "ม.ค.": "มกราคม 2026",
  "ก.พ.": "กุมภาพันธ์ 2026",
  "มี.ค.": "มีนาคม 2026",
};

export const MONTH_NUMBERS: Record<string, number> = {
  "ม.ค.": 1,
  "ก.พ.": 2,
  "มี.ค.": 3,
};

export const STATUS_LABELS: Record<WorkStatus, string> = {
  completed: "เสร็จสิ้น",
  pending: "รอดำเนินการ",
  cancelled: "ยกเลิก",
};

export const PRODUCTS = [
  "SenseFace 4A",
  "SenseFace 3A",
  "SenseFace 2A",
  "EFace10",
  "K60",
  "MB40_VL_ID",
  "MB10_VL_ID",
  "MB10",
  "Biotime",
  "ZKTeco",
  "อื่นๆ",
];

export const OS_LIST = [
  "Windows 11",
  "Windows 10",
  "Windows Server",
  "Linux",
  "อื่นๆ",
];
